version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2017 Preview
before_build:
- cmd: nuget restore src/Inshapardaz.Api.sln
- cmd: cd src/Inshapardaz.api/wwwroot
- cmd: npm install
- cmd: npm run build
- cmd: cd ../../..
build:
  project: src/Inshapardaz.api.sln
  publish_wap_xcopy: true
  verbosity: minimal
after_build:
- cmd: dotnet publish -c Release src/inshapardaz.api/inshapardaz.api.csproj
test_script:
- cmd: cd src/Inshapardaz.UnitTests
- cmd: dotnet test --no-build
- cmd: cd ../Domain.UnitTests
- cmd: dotnet test --no-build
artifacts:
- path: src\Inshapardaz\bin\Release\netcoreapp2.0\publish
  name: api
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://ipapi.scm.azurewebsites.net:443/msdeploy.axd?site=ipapi
  website: ipapi
  username: $ipapi
  password:
    secure: vK/BUACA1BgRsWc0a6hLQ2xgw71Ip04EWgk0Kfbx6RewUyDHbH7E32UDSeb0XXyU3SaP3W6DJCILfvCS0Yyuyg==
  artifact: api
  aspnet_core: true
  remove_files: true
  app_offline: true
  do_not_use_checksum: true
  aspnet_core_force_restart: true