version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019

environment:
  DefaultDatabase:
    secure: xRPJOkFVcWlOPF0wlbbRsjmPXiDSnTjd03Q4aM6bI1hjzjjUsH4wxNSJRnuH3DT9Z3x+fGXmdVdgexKx/ghFpC6znjlEgoE8gL00q86zZ+xcE3piP/6IfH8YutYJ5+OdgOS027eYbt2Ao+LmoZyjy1bGEr3af8wr1NwJrhsHshuzlNrUIpLZ4rbjuMqfiNofNLACeTJ5pif6Z00v2pSRLyEz9QnemZdtwM+zKV9IURTB9UHJFPf36DeaaVU6LCCDMMUCbgVcr1R8rxTnl2UgXZKqX7Q33/Gb2A6VEf/bm7OaqWmr/xAKRzgvInnEcftT

skip_tags: true
skip_branch_with_pr: true

#Before the build starts
before_build:
- cmd: dotnet restore ./Inshapardaz.Api.sln

# Building
build_script:
  - cmd: dotnet publish -c Release src/Inshapardaz.Functions/Inshapardaz.Functions.csproj

# Testing
test_script:
- cmd: cd src/Inshapardaz.Functions.Tests
- cmd: dotnet test --test-adapter-path:. --logger:Appveyor

# Create artifacts
artifacts:
- path: src/Inshapardaz.Functions/bin/Release/netcoreapp2.1/publish/
  name: Function

# Deployment
deploy:
- provider: WebDeploy
  server: https://api-inshapardaz.scm.azurewebsites.net:443/msdeploy.axd?site=api-inshapardaz
  website: api-inshapardaz
  username: $api-inshapardaz
  password:
    secure: JtybVbpTxTWp21oT11L4dL7KzpGW6DAovgmyo4Gw9iX0wKUuZd2vzN7t6stoUucU7tyLCFHsCEQ3yiiiulR18A==
  artifact: Function
  on:
    branch: master
