version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019

environment:
  DefaultDatabase:
    secure: xRPJOkFVcWlOPF0wlbbRsjmPXiDSnTjd03Q4aM6bI1hjzjjUsH4wxNSJRnuH3DT9Z3x+fGXmdVdgexKx/ghFpC6znjlEgoE8gL00q86zZ+xcE3piP/6IfH8YutYJ5+OdgOS027eYbt2Ao+LmoZyjy1bGEr3af8wr1NwJrhsHshuzlNrUIpLZ4rbjuMqfiNofNLACeTJ5pif6Z00v2pSRLyEz9QnemZdtwM+zKV9IURTB9UHJFPf36DeaaVU6LCCDMMUCbgVcr1R8rxTnl2UgXZKqX7Q33/Gb2A6VEf/bm7OaqWmr/xAKRzgvInnEcftT
  EmailFrom:
    secure: 3FKyS0RrrvieTzdM120Mt29HUFnRBXfh7z/GaQCtrlE=
  EmailFromName: "Nawishta"
  SmtpHost: 
    secure: H5AOjEOr8eaZiqYsK/4RUDiJebjsn5BPB4W5JLWdeDA=
  SmtpPort:
    secure: 2yZeZjV9OpoP+muF5RfW0w==
  SmtpUser: 
    secure: REi8f7in30iqJiCZ0sTVa76mo+RBH7JbFH/98INkbmz1XytxhVJg5ASaZVCId24E
  SmtpPass: 
    secure: qJv2I2x4hS7Vf4qiyW1/1gFSS0vi5xHLVv8iFodoU5PPFd3KxEF36xJK8d4t65r+
  Secret:
    secure: fwzDxCo5A5oNaUE8Zs5IHftRI17nskUr0G5kTMd/UYyq1cKEDT+1SeJzSH5cGNwt
    
skip_tags: true
skip_branch_with_pr: true

#Before the build starts
before_build:
- cmd: dotnet restore ./Inshapardaz.Api.sln

# Building
build_script:
  - cmd: dotnet publish -c Release src/Inshapardaz.Api/Inshapardaz.Api.csproj

# Testing
test_script:
- cmd: cd src/Inshapardaz.Api.Tests
#- cmd: dotnet test --test-adapter-path:. --logger:Appveyor

# Create artifacts
artifacts:
- path: src/Inshapardaz.Api/bin/Release/netcoreapp5.0/publish/
  name: APIPackage

# Deployment
deploy:
- provider: WebDeploy
  server: https://api-nawishta.scm.azurewebsites.net:443/msdeploy.axd?site=api-nawishta
  website: api-library
  username: $api-nawishta
  password:
    secure: lBdR5hKd5QzhZfAakenkg3/E6ES59+8ueaWLFhPfFoGATilxS4jfjKiKr8EbcBJqroAq1Lj5qtkLHT/pXlMYhQ==
  artifact: APIPackage
  on:
    branch: master
