version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2017 Preview
before_build:
- cmd: dotnet restore src/Inshapardaz.Api.sln
build:
  project: src/Inshapardaz.api.sln
  publish_wap_xcopy: true
  verbosity: minimal
after_build:
- cmd: dotnet publish -c Release src/inshapardaz.api/inshapardaz.api.csproj
test_script:
- cmd: cd src/Inshapardaz.Api.UnitTests
- cmd: dotnet test --no-build
#- cmd: cd ../Inshapardaz.Api.IntegrationTests
#- cmd: dotnet test --no-build
artifacts:
- path: src\Inshapardaz.Api\bin\Release\netcoreapp2.0\publish
  name: api
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://api-inshapardaz.scm.azurewebsites.net:443/msdeploy.axd?site=api-inshapardaz
  website: api-inshapardaz
  username: $api-inshapardaz
  password: 9vW7BrBPgX6qJi4xK8mwvJuFfvXN6TXuJod4lefJbr8uK4kK3SgJHhsfA4QN
  artifact: api
  aspnet_core: true
  remove_files: true
  app_offline: true
  do_not_use_checksum: true
  aspnet_core_force_restart: true