version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019

environment:
  DefaultDatabase:
    secure: xRPJOkFVcWlOPF0wlbbRsjmPXiDSnTjd03Q4aM6bI1hjzjjUsH4wxNSJRnuH3DT9Z3x+fGXmdVdgexKx/ghFpC6znjlEgoE8gL00q86zZ+xcE3piP/6IfH8YutYJ5+OdgOS027eYbt2Ao+LmoZyjy1bGEr3af8wr1NwJrhsHshuzlNrUIpLZ4rbjuMqfiNofNLACeTJ5pif6Z00v2pSRLyEz9QnemZdtwM+zKV9IURTB9UHJFPf36DeaaVU6LCCDMMUCbgVcr1R8rxTnl2UgXZKqX7Q33/Gb2A6VEf/bm7OaqWmr/xAKRzgvInnEcftT

skip_tags: true
skip_branch_with_pr: true

#Before the build starts
before_build:
- cmd: dotnet restore ./Inshapardaz.Api.sln

# Building
build_script:
  - cmd: dotnet publish -c Release src/Inshapardaz.Api/Inshapardaz.Api.csproj

# Testing
test_script:
- cmd: cd src/Inshapardaz.Api.Tests
#- cmd: dotnet test --test-adapter-path:. --logger:Appveyor

# Create artifacts
artifacts:
- path: src/Inshapardaz.Api/bin/Release/netcoreapp3.1/publish/
  name: APIPackage

# Deployment
deploy:
- provider: WebDeploy
  server: https://api-nawishta.scm.azurewebsites.net:443/msdeploy.axd?site=api-nawishta
  website: api-library
  username: $api-nawishta
  password:
    secure: lBdR5hKd5QzhZfAakenkg3/E6ES59+8ueaWLFhPfFoGATilxS4jfjKiKr8EbcBJqroAq1Lj5qtkLHT/pXlMYhQ==
  artifact: APIPackage
  on:
    branch: master
