version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019

environment:
  Secret:
    secure: 39An8kKFcEGarNaOjR6GujpfOMIaEB8FvykWr03ULAh2H9Zfgk/Avt7clWc0JSkd
  EmailFrom:
    secure: 0KUaQyV3RXkLLfkDz/R4NHqXw4LbFaKr3w+FT/oSSWc=
  EmailFromName: "Nawishta"
  SmtpHost: 
    secure: WZuKDTgs3/FfxnCUbBdnvNioVUUPs0ZovWC5zscDbtw=
  SmtpPort:
    secure: TLW9xueDYxnKSi4/tK0d4g==
  SmtpUser: 
    secure: 0KUaQyV3RXkLLfkDz/R4NHqXw4LbFaKr3w+FT/oSSWc=
  SmtpPass: 
    secure: QHbuppDOx4icKiDHpOoEIA==
  DefaultConnection:
    secure: /QAHrKVU6z5bQ9+vnbYAk6uITnSYQQZP85hnKJXpXAB46mqR2xDA5o8KU7Ooz6abxLOpR3f13j04wAvKVoGwKgqruyU+Jlzlx1V6rL9/gGWz7nj8a3EqprjSXks3JVWCThtmPrpppZj3hYzBfmGCiSPo43S3cbEdCejDBbhB/TY=
    
skip_tags: true
skip_branch_with_pr: true

#Before the build starts
before_build:
- cmd: dotnet restore ./Inshapardaz.Api.sln

# Building
build_script:
  - cmd: dotnet publish -c Release src/Inshapardaz.Api/Inshapardaz.Api.csproj

# Testing
test_script:
- cmd: cd src/Inshapardaz.Api.Tests
#- cmd: dotnet test --test-adapter-path:. --logger:Appveyor

# Create artifacts
artifacts:
- path: src/Inshapardaz.Api/bin/Release/netcoreapp5.0/publish/
  name: APIPackage

# Deployment
deploy:
  - provider: WebDeploy
    server: 
      secure: u8wIDIPypO+MQ0FwToHf6wj4cw+T7GL50YSxrj8K2P84R2iet2iBTYhQBQWJlqgWmy9nvWTjew97gc8H2/rFnI8TuBBZ/h/a93HAEZlhkKo=
    website: 
      secure: K2wVnSHPf9n6SLDp8chOmQ==
    username: 
      secure: BkN+6uQ3Cmoe1g+c60WFqPB8299X25/h1YH0oNzzFoA=
    password: 
      secure: ALS2iQsptYanrFZtGn1oWA==
    remove_files: true
    app_offline: true
    artifact: APIPackage
    on:
      branch: master
