version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2019

skip_tags: true
skip_branch_with_pr: true

#Before the build starts
before_build:
- cmd: dotnet restore ./Inshapardaz.Api.sln

# Building
build_script:
  - cmd: dotnet publish -c Release src/Inshapardaz.Api/Inshapardaz.Api.csproj

# Testing
test_script:
- cmd: cd src/Inshapardaz.Api.Tests
#- cmd: dotnet test --test-adapter-path:. --logger:Appveyor

# Create artifacts
artifacts:
- path: src/Inshapardaz.Api/bin/Release/netcoreapp5.0/publish/
  name: APIPackage

# Deployment
deploy:
  - provider: WebDeploy
    server: 
      secure: u8wIDIPypO+MQ0FwToHf6wj4cw+T7GL50YSxrj8K2P84R2iet2iBTYhQBQWJlqgWmy9nvWTjew97gc8H2/rFnI8TuBBZ/h/a93HAEZlhkKo=
    website: 
      secure: K2wVnSHPf9n6SLDp8chOmQ==
    username: 
      secure: BkN+6uQ3Cmoe1g+c60WFqPB8299X25/h1YH0oNzzFoA=
    password: 
      secure: jU+awrC8RsQPYFEau8nNrw==
    remove_files: true
    artifact: APIPackage
    on:
      branch: master
