version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2017 Preview
before_build:
- cmd: dotnet restore src/Inshapardaz.Api.sln
- cmd: cd src/Inshapardaz.api/wwwroot
- cmd: npm install
- cmd: npm run build
- cmd: cd ../../..
build:
  project: src/Inshapardaz.api.sln
  publish_wap_xcopy: true
  verbosity: minimal
after_build:
- cmd: dotnet publish -c Release src/inshapardaz.api/inshapardaz.api.csproj
test_script:
- cmd: cd src/Inshapardaz.Api.UnitTests
- cmd: dotnet test --no-build
- cmd: cd ../Inshapardaz.Domain.UnitTests
- cmd: dotnet test --no-build
artifacts:
- path: src\Inshapardaz.Api\bin\Release\netcoreapp2.0\publish
  name: api
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://ipapi.scm.azurewebsites.net:443/msdeploy.axd?site=ipapi
  website: ipapi
  username: $ipapi
  password: L6iRu7xou062FovaspAHlwDhNkJbCbk6mheJtwCv38WzAuTeD805aT9nfu7T
  artifact: api
  aspnet_core: true
  remove_files: true
  app_offline: true
  do_not_use_checksum: true
  aspnet_core_force_restart: true