services:
  smtp:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8025/api/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    build: 
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on: 
      - db
    expose: 
      - "5000"
    ports:
      - "5000:5000"
  db:
    image: 'mcr.microsoft.com/mssql/server'
    restart: always
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - './drive:/var/opt/mssql'
