version: '3.1'

services:
  smtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:1025"]
    user: root
    ports:
      - 8025:8025
      - 1025:1025
    healthcheck:
      test: echo | telnet 127.0.0.1 1025
  api:
    build: 
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on: 
      - db
    expose: 
      - "5000"
    ports:
      - "5000:5000"
  db:
    image: 'mcr.microsoft.com/mssql/server'
    restart: always
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - './drive:/var/opt/mssql'
