<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="dapper" Version="2.1.72" />
    <PackageReference Include="FluentMigrator.Runner.MySql" Version="5.2.0" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\db\Inshapardaz.Database.Migrations\Inshapardaz.Database.Migrations.csproj" />
    <ProjectReference Include="..\..\..\Inshapardaz.Domain\Inshapardaz.Domain.csproj" />
  </ItemGroup>

</Project>
